name: Mapping

# Trigger the workflow when the pull request for version change is merged/closed.
on:
  push:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Notification message'
        required: true
  
jobs:
  notification:
    runs-on: ubuntu-latest
    
    steps:
      # Check-out 'development' repository to our action  
      - uses: actions/checkout@v3
    

      - name: 'Call API'
        uses: actionsflow/axios@v1
        id: api
        with:
            url: http://127.0.0.1:8000/
            #method: 'POST'
            data: '{ "domain":"google" }'
            is_debug: true
          
    
