name: Mapping

# Trigger the workflow when the pull request for version change is merged/closed.
on:
  push:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Notification message'
        required: true
      id:
        description: 'run identifier'
        required: false
  
jobs:
  notification:
    runs-on: ubuntu-latest
    
        
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}
      # Check-out 'development' repository to our action  
      - uses: actions/checkout@v3
    
      - name: Install curl
        run: |
          apt-get update; apt-get install -y curl

   
            
    
    
