name: Trigger 

on:
  workflow_dispatch:
   inputs:
      domain:
        description: 'Notification needed'
        required: true
 

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Create Nginx Config
        run:  |
              echo "server { listen 80; server_name ${{ github.event.inputs.domain }}; 
              location / { # Your configuration here }
              location /location2 {
                    # Configuration for location2
                  }
                  }" > ${{ github.event.inputs.domain }}.conf
              cat ${{ github.event.inputs.domain }}.conf
              ls -la

      - name: Run My Workflow
        run: |
             apt-get update
             apt-get install certbot
             apt-get install python3-certbot-nginx
             certbot --nginx -d ${{ github.event.inputs.domain }}
