name: Mapping

# Trigger the workflow when the pull request for version change is merged/closed.
on:
  push:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Notification message'
        required: true
  
jobs:
  notification:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
     postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      # Check-out 'development' repository to our action  
      - uses: actions/checkout@v3
    
      - name: Install curl
        run: |
          apt-get update; apt-get install -y curl

      - name: Make HTTP request to ngrok URL
        run: |
          CURL -X POST -H "Content-Type: application/json" \
            -d '{ "domain":"google"}' \
            http://localhost:8000/validate/
            
    
    
