name: Trigger 

on:
  push:
 

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Nginx Config
        run:  |
              echo "server { listen 80; server_name ${{ secrets.DOMAIN_NAME }}; location / { # Your configuration here } }" > ${{ secrets.DOMAIN_NAME }.conf
              cat ${{ secrets.DOMAIN_NAME }}.conf

      - name: Run My Workflow
        run: |
          # Insert the steps of your workflow here
