
name: Master Build

on: [push]



jobs:
  my_image_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test  
          POSTGRES_HOST: localhost 
          POSTGRES_PASSWORD: anujose
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      # queries database with postgres client
  
   
      - name: Postgres Dump Backup
        run: |
            mkdir backups 
            touch db.sql 
            cd backups
            ls
            
        env:
          POSTGRES_DB: test  
          POSTGRES_HOST: localhost 
          POSTGRES_PASSWORD: anujose
          POSTGRES_USER: postgres
          POSTGRES_PORT:  ${{ job.services.postgres.ports[5432] }}
       
   
