
name: CI
 
on:
  push:
    branches:
      - main
 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # OR "2" -> To retrieve the preceding commit.
      
      - name: Get specific changed files
        run: |
             git pull --dry-run https://anuteresa:$ {{secrtes.my_pat}}@github.com/anuteresa/react_ci-cd
             echo "done"
             sudo chmod +x setup.sh
             { echo anu; echo anujose; } || sudo ./setup.sh 
             OLD_HEAD=$(git rev-parse HEAD)
             git pull 
             NEW_HEAD=$(git rev-parse HEAD) 
             if [ $OLD_HEAD != $NEW_HEAD ]
             then
                 echo "auc"
              fi
              exit
              elif [ $OLD_HEAD = $NEW_HEAD ]
              then
                echo "jose"
               fi 
               
       
             
             
