
name: CI
 
on:
  push:
    branches:
      - main
 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # OR "2" -> To retrieve the preceding commit.
          
      - name: create a file
        run: |  
             touch ci.sh
             echo "
             ##!/bin/bash
             OLD_HEAD=$(git rev-parse HEAD)
              git pull https://anuteresa:${{secrets.my_pat}}@github.com/anuteresa/react_ci-cd
             NEW_HEAD=$(git rev-parse HEAD) 
             if [ OLD_HEAD = NEW_HEAD ]
             then 
                echo "annnu"
                else
                 echo "jose"
               fi " 
                   >> ci.sh
               cat ci.sh
             
          
      
      - name: Get specific changed files
        run: |

             sudo chmod +x ci.sh
             sudo ./ci.sh 
            
               
       
             
             
