
name: Master Build

on: [push]

env:
 
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: anujose

jobs:
  my_image_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name : dump data
        run: |
             pwd
             touch  C:/Program Files/PostgreSQL/14/backups/backup.sql
             pg_dump test > backup.sql
