
name: Master Build

on: [push]



jobs:
  my_image_test:
    runs-on: ubuntu-latest

    

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      
        

      # queries database with postgres client
  
   
      - name: Postgres Dump Backup
        run: |
             ls
             touch db.sql
             ls
             PGPASSWORD="anujose" pg_dump -h localhost -p 5432  -U postgres -d test> db.sql
             cat db.sql
 
             

       
       
   
