
name: CI
 
on:
  push:
    branches:
      - main
 

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v32
        with:
          files: |
            package.json
