
name: CI
 
on:
  pull_request:
    branches:
      - main
 
env:
  token: ${{ secrets.my_pat }}
jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # OR "2" -> To retrieve the preceding commit.
          

             
          
      
      - name: Get specific changed files
        run: |

             sudo chmod +x setup.sh
             sudo ./setup.sh 
             
             git diff --name-only $OLD_HEAD $NEW_HEAD |
                 while read name; do
                 if [ "$name" = "Pipfile.lock" ];
                 then
                   docker build;
            
               
       
             
             
