
name: CI
 
on:
  push:
    branches:
      - main
 

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # OR "2" -> To retrieve the preceding commit.
      
      - name: Get specific changed files
        run: |
             OLD_HEAD=$(git rev-parse HEAD)
             git pull 
             NEW_HEAD=$(git rev-parse HEAD) 
             if [ $OLD_HEAD = $NEW_HEAD ]
             then
                 echo "anu"
              fi
             
              { echo prod; echo anu; } | ./setup.sh.
