
name: Master Build

on: [push]



jobs:
  my_image_test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test  
          POSTGRES_HOST: localhost 
          POSTGRES_PASSWORD: anujose
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      -   name: Install pg_dump
          run: sudo apt-get install postgresql-client -y
        

      # queries database with postgres client
  
   
      - name: Postgres Dump Backup
        shell: bash
        run: |
             ls
             mkdir -p $(dirname backups/backup.sql)
           
             PGPASSWORD="anujose" pg_dump -s -h localhost -p 5432  -U postgres -d test -N _timescaledb_internal | grep -v _timescaledb_internal  > backups/backup.sql

 
             cat backups/backup.sql
        env:
          POSTGRES_DB: test  
          POSTGRES_HOST: localhost 
          POSTGRES_PASSWORD: anujose
          POSTGRES_USER: postgres  
          
      
 
             

       
       
   
