
name: Master Build

on: [push]



jobs:
  my_image_test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test  
          POSTGRES_HOST: localhost 
          POSTGRES_PASSWORD: anujose
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      
        

      # queries database with postgres client
  
   
      - name: Postgres Dump Backup
        run: |
             ls
             touch db.sql
             ls
             PGPASSWORD="anujose" pg_dump -h localhost -p 5432  -U postgres -F -d test  db.sql
             cat db.sql
        env:
          POSTGRES_DB: test  
          POSTGRES_HOST: localhost 
          POSTGRES_PASSWORD: anujose
          POSTGRES_USER: postgres      
 
             

       
       
   
