on:
  push:

jobs:
  version-check:
    runs-on: ubuntu-latest
    
    steps: 
   
       
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check  
        uses: EndBug/version-check@v2.1.1
      
      - name: Get current package version
        id: extract_version
        uses: martinbeentjes/npm-get-version-action@v1.2.3

      # From now you can access the version
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.current-version }}
