on:
  push:

jobs:
  version-check:
    runs-on: ubuntu-latest
    
    steps: 
   
       
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check  
        uses: EndBug/version-check@v2.1.1
      
      - id: get_version
        uses: battila7/get-version-action@v2

      - run: echo ${{ steps.get_version.outputs.version }}
