on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]
    paths:
     - 'package.json'

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.check.outputs.changed }} == 'true'
    
    steps: 
   
       
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check  
        uses: EndBug/version-check@v2.1.1
      
      - name: Get the release version
        if: steps.check.outputs.changed == 'true'
        id: get_version
        run:  |
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      - name: version 
        run: 
          echo "version =${{ steps.check.outputs.version}}"
  notify-success:
    runs-on: ubuntu-latest
    if: success()
    needs: [version-check]
    steps:
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check  
        uses: EndBug/version-check@v2.1.1
      - name: Notify slack success
        if: steps.check.outputs.changed == 'true'
        run: echo "success"
