on:
  release:

jobs:
  version-check:
    runs-on: ubuntu-latest
    
    steps: 
   
       
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check  
        uses: EndBug/version-check@v2.1.1
      
      - name: Get the release version
        id: get_version
        run:  |
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      - name: version 
        run: 
          echo "version =${{ steps.get_version.outputs.VERSION }}"
