
name: filetest
 
on:
  push:


 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # OR "2" -> To retrieve the preceding commit.
          

             
          
      
      - name: Get specific changed files
        run: |
             touch be-staging-environment
             ls -la
             
      - name: Get specific changed files
        run: |
             mv be-staging-environment .env
             ls -la
