on:
  
  push:
    branches:
      - main
 
jobs:
  run-build-if-needed:
   runs-on: ubuntu-latest   
    
   steps: 
      - uses: actions/checkout@v3
    

 
       
               
         
      - name: Download lokalise translations
        run: |
          docker run -v /tmp/lokalise:/opt/dest lokalise/lokalise-cli-2 lokalise2 \
          --token "e1c60528902a5a3c4a1e257d9b8f2bc7a72f43f7" \
          --project-id 1002082764c25a286c0de3.61986318 file download \
          --format json_structured \
          --unzip-to /opt/dest \
          --original-filenames=false \
          --export-sort a_z \
          --placeholder-format icu \
          --json-unescaped-slashes=true \
          --indentation 2sp \
          --export-empty-as base \
          --add-newline-eof \
          --replace-breaks=false
             
      - name: Move new translations
        run: |
             ls -la
             cp /tmp/lokalise/locale/* ./translations/app  
  #    - name: 🏗 Set up 
   #     uses: frenck/action-setup-lokalise@v1
    #  - name: Frenck's Lokalise CLI setu
     #   uses: onin-engineering/lokalise-download-action@v1.0.1
      #  with:
       #    lokalise-token: 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd
        #   lokalise-project-id: "6425482963873698913302.34331656"
         #  format: json
          # file-path: ./translations
           #bundle-structure: /%LANG_ISO%.json
          # original-filename: false
          # directory-prefix : "values-%LANG_ISO%"
          # placeholder-format: printf

           
  
      - name: Create Pull Request
        if: steps.check.outputs.changed == 'true'
        id: demo-pr
        uses: peter-evans/create-pull-request@v4
        
      
        
      - name: Approve Pull Request
        if: ${{ steps.demo-pr.outputs.pull-request-number }}
        uses: juliangruber/approve-pull-request-action@v2.0.3
        with:
         github-token: ${{ secrets.PAT }}
         number: ${{ steps.demo-pr.outputs.pull-request-number }}
      - name: Merge Pull Request
        if:  ${{ steps.demo-pr.outputs.pull-request-number }}
        uses: juliangruber/merge-pull-request-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.demo-pr.outputs.pull-request-number }}
          method: squash   
  
     


  run-build:
  
    runs-on: ubuntu-latest 
    if: success()
    needs: [run-build-if-needed]
    strategy:
      matrix:
       include:
           - REACT_APP_API_URL: https://staging
           - REACT_APP_WEBSITE_URL: https://staging.anu
             REACT_APP_RT: anu
             REACT_APP: JOSE
    steps:
      - uses: actions/checkout@v3

         
      - name: Create Pull 
        run: |
             ls -la
             cd translations
             cd app
             cat en.json
                 
         
        
     # - name:  Use Lokalise
      #  run: |
       #     lokalise2 --version
        #    lokalise2  file download --token 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd --project-id 6425482963873698913302.34331656 --export-empty-as skip --export-sort first_added --format xml --unzip-to "./translations" --directory-prefix "values-%LANG_ISO%" --original-filenames false
  
      #- name: Pull translations

       # run: |
        #      curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
         #     lokalise2 \
          #       file download \
           #      --token 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd \
            #     --project-id 6425482963873698913302.34331656 \
             #    --format json \
              #    --unzip-to ./locales
            #  lokalise2  file download --token 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd --project-id 6425482963873698913302.34331656 --export-empty-as skip --export-sort first_added --format xml --unzip-to "./translations" --directory-prefix "values-%LANG_ISO%" --original-filenames false
 
