on:

 workflow_dispatch:
 
jobs:
  run-build-if-needed:
   runs-on: ubuntu-latest   
    
   steps: 
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Install Dependencies
        run: yarn install
         
      - name: Download lokalise translations
        run: |
          docker run -v /tmp/lokalise:/opt/dest lokalise/lokalise-cli-2 lokalise2 \
          --token "e1c60528902a5a3c4a1e257d9b8f2bc7a72f43f7" \
          --project-id 1002082764c25a286c0de3.61986318 file download \
          --format json_structured \
          --unzip-to /opt/dest \
          --original-filenames=false \
          --export-sort a_z \
          --placeholder-format icu \
          --json-unescaped-slashes=true \
          --indentation 2sp \
          --export-empty-as base \
          --add-newline-eof \
          --replace-breaks=false
          
      - name: Move new translations
        run: |
             ls -la
             cp /tmp/lokalise/locale/* ./translations/app 

      - name: Fetch Lokalisations and Check for Changes
        run: |
    
           if git diff --exit-code; then
            echo "No changes found."
           else
            echo "Changes detected. Staging and committing..."   
            git add ./translations/app
            yarn version --patch
            yarn publish
           fi

       
  #    - name: 🏗 Set up 
   #     uses: frenck/action-setup-lokalise@v1
    #  - name: Frenck's Lokalise CLI setu
     #   uses: onin-engineering/lokalise-download-action@v1.0.1
      #  with:
       #    lokalise-token: 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd
        #   lokalise-project-id: "6425482963873698913302.34331656"
         #  format: json
          # file-path: ./translations
           #bundle-structure: /%LANG_ISO%.json
          # original-filename: false
          # directory-prefix : "values-%LANG_ISO%"
          # placeholder-format: printf

           
  
    
