on:
  
  pull_request:
    types:
      - closed
    branches: [ "main" ]
    paths:
     - 'package.json'
 
jobs:
  run-build-if-needed:
  
    runs-on: ubuntu-latest   
    
    steps: 
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Check if version has been updated
        id: check  
        uses: EndBug/version-check@v2.1.1
       
   

     
        
      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'

               
         
      - name: Download lokalise translations
        if: steps.check.outputs.changed == 'true'
        run: |
          docker run -v /tmp/lokalise:/opt/dest lokalise/lokalise-cli-2 lokalise2 \
          --token "633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd" \
          --project-id 6425482963873698913302.34331656 file download \
          --format json_structured \
          --unzip-to /opt/dest \
          --original-filenames=false \
          --export-sort a_z \
          --placeholder-format icu \
          --json-unescaped-slashes=true \
          --indentation 2sp \
          --export-empty-as base \
          --add-newline-eof \
          --replace-breaks=false
             
      - name: Move new translations
        if: steps.check.outputs.changed == 'true'
        run: |
             ls -la
             cp /tmp/lokalise/locale/* ./translations/app  
  #    - name: 🏗 Set up 
   #     uses: frenck/action-setup-lokalise@v1
    #  - name: Frenck's Lokalise CLI setu
     #   uses: onin-engineering/lokalise-download-action@v1.0.1
      #  with:
       #    lokalise-token: 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd
        #   lokalise-project-id: "6425482963873698913302.34331656"
         #  format: json
          # file-path: ./translations
           #bundle-structure: /%LANG_ISO%.json
          # original-filename: false
          # directory-prefix : "values-%LANG_ISO%"
          # placeholder-format: printf

           
  
      - name: Create Pull Request
        if: steps.check.outputs.changed == 'true'
        id: demo-pr
        uses: peter-evans/create-pull-request@v4
        
      
        
      - name: Approve Pull Request
        if: ${{ steps.demo-pr.outputs.pull-request-number }}
        uses: juliangruber/approve-pull-request-action@v2.0.3
        with:
         github-token: ${{ secrets.PAT }}
         number: ${{ steps.demo-pr.outputs.pull-request-number }}
      - name: Merge Pull Request
        if:  ${{ steps.demo-pr.outputs.pull-request-number }}
        uses: juliangruber/merge-pull-request-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.demo-pr.outputs.pull-request-number }}
          method: squash   
  
     


  run-build:
  
    runs-on: ubuntu-latest 
    if: success()
    needs: [run-build-if-needed]
    strategy:
      matrix:
       include:
           - REACT_APP_API_URL: https://staging
           - REACT_APP_WEBSITE_URL: https://staging.anu
             REACT_APP_RT: anu
             REACT_APP: JOSE
    steps:
      - uses: actions/checkout@v3
        with:
         ref: development
       
      - name: Check if version has been updated
        id: check  
        uses: EndBug/version-check@v2.1.1
       
      


     
        
      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'

         
      - name: Create Pull 
        run: |
             ls -la
             cd translations
             cd app
             cat en.json
                 
         
        
     # - name:  Use Lokalise
      #  run: |
       #     lokalise2 --version
        #    lokalise2  file download --token 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd --project-id 6425482963873698913302.34331656 --export-empty-as skip --export-sort first_added --format xml --unzip-to "./translations" --directory-prefix "values-%LANG_ISO%" --original-filenames false
  
      #- name: Pull translations

       # run: |
        #      curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
         #     lokalise2 \
          #       file download \
           #      --token 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd \
            #     --project-id 6425482963873698913302.34331656 \
             #    --format json \
              #    --unzip-to ./locales
            #  lokalise2  file download --token 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd --project-id 6425482963873698913302.34331656 --export-empty-as skip --export-sort first_added --format xml --unzip-to "./translations" --directory-prefix "values-%LANG_ISO%" --original-filenames false
 
