on:
 push:
 
jobs:
  run-build-if-needed:
   runs-on: ubuntu-latest   
    
   steps: 
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

       # Get branch name
      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT  
        
      # Get branch name
      - name: Get branch name
        id: branch1
        run: echo   ${{ steps.branch.outputs.BRANCH_NAME }}
     
      - name: Download lokalise translations
        run: |
          cat ./translations/app/en.json
          docker run -v /tmp/lokalise:/opt/dest lokalise/lokalise-cli-2 lokalise2 \
          --token "e1c60528902a5a3c4a1e257d9b8f2bc7a72f43f7" \
          --project-id 1002082764c25a286c0de3.61986318 file download \
          --format json_structured \
          --unzip-to /opt/dest \
          --original-filenames=false \
          --export-sort a_z \
          --placeholder-format icu \
          --json-unescaped-slashes=true \
          --indentation 2sp \
          --export-empty-as base \
          --add-newline-eof \
          --replace-breaks=false
          
          
      - name: Move new translations
        run: |
             ls -la
             cp /tmp/lokalise/locale/* ./translations/app 

      - name: Set Git Identity
        run: |
          git config --global user.email "anuteresaj@gmail.com"
          git config --global user.name "anuteresa"        

      - name: Fetch Lokalisations and Check for Changes
        run: |
           cat ./translations/app/en.json
         
           CHANGES=$(git status --porcelain)
           if [ -n "$CHANGES" ]; then    
            echo " changes found."
            git add ./translations/app
            yarn version --patch
            git push origin main --tags 
           else
            echo "No Changes detected".   
            
            
            
           fi

       
  #    - name: 🏗 Set up 
   #     uses: frenck/action-setup-lokalise@v1
    #  - name: Frenck's Lokalise CLI setu
     #   uses: onin-engineering/lokalise-download-action@v1.0.1
      #  with:
       #    lokalise-token: 633896f181ccf6613e1d44fa6a2d1dbc00fa1dcd
        #   lokalise-project-id: "6425482963873698913302.34331656"
         #  format: json
          # file-path: ./translations
           #bundle-structure: /%LANG_ISO%.json
          # original-filename: false
          # directory-prefix : "values-%LANG_ISO%"
          # placeholder-format: printf

           
  
    
