# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "edw" ]
    paths:
     - 'package.json'
 
    
    
     
    
  pull_request:
    branches: [ "main" ]

jobs:
  run-build-if-needed:
    runs-on: ubuntu-latest
    steps:
    - uses: MontyD/package-json-updated-action@1.0.1

      id: version-updated
      with:
        path: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      if: steps.version-updated.outputs.has-updated
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v3
      if: steps.version-updated.outputs.has-updated
      with:
        node-version: '16.x'
 

    - name: Install
      if: steps.version-updated.outputs.has-updated
      run: |
          yarn
          yarn test
      env:
         NODE_AUTH_TOKEN: ${{ secrets.my_pat}}
    - name : Build  
      if: steps.version-updated.outputs.has-updated
      run: |
           yarn build
           ls
           cat package.json
           
   
    
 
        
    


 
    
 
