on:
  push:
name: Continuous integration
jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: package.json
  
        id: version_check_staging
      - name: check
        if: ${{steps.version_check_staging.outputs.versionChanged}} == 'true'
        run: |
             echo "Version ${{steps.version_check_staging.outputs.versionChanged}}"
