# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pull-request:

    runs-on: macos-latest

    

    steps:
    - uses: actions/checkout@v3
    - name: checkout
      uses: react_ci-cd/pull-request@v3
    - name: pull-request
      with:
        destination_branch: "main"


