name: Test Nginx Configuration

on:
  push:
    branches: [ main ]    
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update draft to 
        run: |
          curl \
            -u user:${{ secrets.PAT }} \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/OWNER/REPO/releases/latest
