name: Test Nginx Configuration

on:
  push:
    branches: [ main ]    
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update draft to 
        run: |
          curl -L \
             -H "Authorization: Bearer ${{ secrets.PAT }}" \           
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/anuteresa/react_ci-cd/releases/latest
