name: Test Nginx Configuration

on:
  push:
    branches: [ main ]    
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Latest Release
        id: fetch_release
        run: |
          curl -sSL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/anuteresa/react_ci-cd/releases/latest > latest_release.json
          latest_tag=$(jq -r '.tag_name' latest_release.json)
