name: Test Nginx Configuration

on:
  push:
    branches: [ main ]    
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: get files
        run: |
           ls -la  

        
      - name: Fetch Latest Release
        id: fetch_release
        run: |
          curl -sSL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/anuteresa/react_ci-cd/releases/latest > latest_release.json
          latest_tag=$(jq -r '.tag_name' latest_release.json)
          echo $latest_tag

      - name: Fetch Latest Release Draft
        id: fetch_draft_release
        run: |
          curl -sSL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/owner/repo/releases | jq -r 'map(select(.draft == true))'
            tag_name=$(echo "${draft_info}" | jq -r '.[0].tag_name')
            echo "Latest Draft Release Tag: $tag_name"
             echo "BRANCH_NAME=${tag_name}" >> $GITHUB_OUTPUT 

      - name: Checkout code from draft release
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.fetch_draft_release.outputs.BRANCH_NAME }}

      - name: get files
        run: |
           ls -la

