

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production CI

on:    
  schedule:
    - cron: '*/15 * * * *'
  

jobs:
  run-build-if-needed:
    runs-on: ubuntu-latest
    strategy:
      matrix:

       include:
           - REACT_APP_API_URL: 'test'
             REACT_APP_WEBSITE_URL: 'staging' 
               
    steps:

    - uses: actions/checkout@v3
 
      with:
        fetch-depth: 1
        ref: 'main'
        

          
    

   
        
    


 
    
 
