

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production CI

on:    
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:
    inputs:
      staging:
        default: "Yes"  
 
        
  

jobs:
  run-build-if-needed:
    runs-on: ubuntu-latest
     
    strategy:
      matrix:

       include:
           - REACT_APP_API_URL: 'test'
             REACT_APP_WEBSITE_URL: 'staging' 
               
    steps:

    - uses: actions/checkout@v3
 
      with:
        fetch-depth: 1
        ref: 'main'
        
    - name: 'Blog Custom Github Action'
      shell: bash
      run: |
            
            yn=${{ github.event.inputs.staging }}
            echo "::set-output name=value::${yn:-"Yes"}"
            sh ./setup.sh


   

        

          
    

   
        
    


 
    
 
