name: Rollback

on:
   # Runs every day at 5 PM UTC (adjust the time zone as needed)
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run:  |
            cat tes.py   
