name: Rollback

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '35 5,15 * * *'
   
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run:  |
            cat tes.py   
