name: Rollback

on:
   
  schedule:
   - cron: '21 5,15 * * *'
   
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run:  |
            cat tes.py   
