
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:

 
    
    
     
  push: 


   branches: [ "main" ]
   paths:
     - 'package.json'

jobs:
 run-build-if-needed:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.version-updated.outputs.has-updated }}
    strategy:
      matrix:

       include:
           - REACT_APP_API_URL: 'test'
           - REACT_APP_API_URL: 'staging'

               
    steps:
    
    
    - uses: MontyD/package-json-updated-action@1.0.1

      id: version-updated
      with:
        path: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    
    - uses: actions/checkout@v3
      if: steps.version-updated.outputs.has-updated
      with:
        fetch-depth: 1
        ref: 'main'
        
    - uses: actions/setup-node@v3
      if: steps.version-updated.outputs.has-updated
      with:
        node-version: '16.x'
              

    - name: Get current package version
    
      if: steps.version-updated.outputs.has-updated
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.2.3
      
      
    - name : display version  
      if: steps.version-updated.outputs.has-updated
      run: | 
           echo ${{ steps.version-updated.outputs.current-package-version}}
           
           
 notify_started:
    runs-on: ubuntu-latest
    if: success()

    steps:         
     - name: started  
       if: steps.version-updated.outputs.has-updated
       run: echo 'started'          
           
 notify:
    runs-on: ubuntu-latest
    
    if: failure() 
    needs: [run-build-if-needed]
    steps:         
    - name: Post to a Slack channel
      if: ${{needs.run-build-if-needed.outputs.output1}}
      
   
      run: echo 'failure'
      
 notify_sucess :  
    runs-on: ubuntu-latest
    
    if: success()
    needs: [run-build-if-needed]
    steps: 
    - name: Post 
      if: ${{needs.run-build-if-needed.outputs.output1}}
      
   
      run: echo 'sucess'
  
      
      
     
      
      
      

           
    
           
   


          
          
    

   
        
    


 
    
 
