
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:

 
    
    
     
  push: 


   branches: [ "main" ]
   paths:
     - 'package.json'

jobs:
  run-build-if-needed:
    runs-on: ubuntu-latest
    strategy:
      matrix:

       include:
           - REACT_APP_API_URL: 'test'
             REACT_APP_WEBSITE_URL: 'staging' 
               
    steps:
    - uses: MontyD/package-json-updated-action@1.0.1

      id: version-updated
      with:
        path: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      if: steps.version-updated.outputs.has-updated
      with:
        fetch-depth: 1
        ref: 'main'
        
    - uses: actions/setup-node@v3
      if: steps.version-updated.outputs.has-updated
      with:
        node-version: '16.x'

 

    - name: Install
      if: steps.version-updated.outputs.has-updated
      run: |
          yarn
          
      env:
         NODE_AUTH_TOKEN: ${{ secrets.my_pat}}
         
         
    - name: Create env file
      run: |
           
           touch .env
           ls
           echo REACT_APP_API_URL=${{ matrix.REACT_APP_API_URL }} > .env
           echo REACT_APP_WEBSITE_URL=${{ matrix.REACT_APP_WEBSITE_URL }} > .env
           cat .env
           
           
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_GITHUB_LOGIN: ${{ matrix.REACT_APP_API_URL }}
        envkey_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ matrix.REACT_APP_WEBSITE_URL }}
      
           
          
               
    - name : Build  
      if: steps.version-updated.outputs.has-updated
      run: |

     
          yarn build
      

           
    
           
   


          
          
    

   
        
    


 
    
 
