name: Get Last Commit Tag and Checkout Another Repo

on:
  push:

jobs:
  get-last-commit-tag:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.get-tag.outputs.version }}

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v2
        with:
          repository: anuteresa/react_ci-cd  # Replace with the actual repository URL

      - name: Get Last Commit Tag
        id: get-tag
        run: |
          git fetch --tags
          echo "version=$(git describe --tags $(git rev-list --tags --max-count=1) 2>&1 || true)" >> "$GITHUB_OUTPUT"
          
  checkout-another-repo:
    needs: get-last-commit-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v2
        with:
          repository: anuteresa/ci-cd  # Replace with the actual repository URL
          ref: main
          token: ${{ secrets.PAT }}

      - name: Display Repository B Contents
        run: |
          echo ${{needs.get-last-commit-tag.outputs.output1}}
          expected_version=$(jq -r '.dependencies."@testing-library/jest-dom"' package.json)
          echo $expected_version
          if [ "${{needs.get-last-commit-tag.outputs.output1}}" = "$expected_version" ]; then
           echo "Versions match!"
          else
           echo "Versions do not match."
          fi

          # Replace with actual commands to interact with Repository B
