name: Get Last Commit Tag and Checkout Another Repo

on:
  push:

jobs:
  get-last-commit-tag:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.get-tag.outputs.version }}

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v2
        with:
          repository: anuteresa/react_ci-cd  # Replace with the actual repository URL

      - name: Get Last Commit Tag
        id: get-tag
        run: |
          git fetch --tags
          tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>&1 || true)
          echo $tag
          echo version=${tag#v}
          echo $version
          echo "version=${tag#v}" >> "$GITHUB_OUTPUT"
          echo 'output'
          echo $version
          
  checkout-another-repo:
    needs: get-last-commit-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v2
        with:
          repository: anuteresa/ci-cd  # Replace with the actual repository URL
          ref: main
          token: ${{ secrets.PAT }}

      - name: Set Git Identity
        run: |
          git config --global user.email "anuteresaj@gmail.com"
          git config --global user.name "anuteresa"        

      - name: Display Repository B Contents
        run: |
          echo ${{needs.get-last-commit-tag.outputs.output1}}
          expected_version=$(jq -r '.dependencies."@testing-library/jest-dom"' package.json)
          echo $expected_version
          if [ "${{needs.get-last-commit-tag.outputs.output1}}" = "^$expected_version" ]; then
           echo "Versions match!"
          else
           echo "Versions do not match."

          echo "Versions do not match. Updating expected version..."


          jq '.dependencies."@testing-library/jest-dom" = "${{needs.get-last-commit-tag.outputs.output1}}"' package.json > tmpfile && mv tmpfile package.json


          git add package.json
          git commit -m "Update @testing-library/jest-dom version to $latest_tag"


          git push origin main

          fi

          # Replace with actual commands to interact with Repository B
