name: Get Last Commit Tag and Checkout Another Repo

on:
  push:

jobs:
  get-last-commit-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v2
        with:
          repository: anuteresa/react_ci-cd  # Replace with the actual repository URL

      - name: Get Last Commit Tag
        id: get-tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)
          if [ -n "$latest_tag" ]; then
           echo "::set-output name=latest_tag::$latest_tag"
          else
           echo "No tags found."
          fi
          

  checkout-another-repo:
    needs: get-last-commit-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v2
        with:
          repository: anuteresa/ci-cd  # Replace with the actual repository URL
          ref: main
          token: ${{ secrets.PAT }}

      - name: Display Repository B Contents
        run: |
          ls -la  
          npm install  # Replace with actual commands to interact with Repository B
