name: unitteststg
 
on:
 push:


 

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      error: ${{ steps.error.outputs.ERROR }}

    steps:
      - uses: actions/checkout@v3
      
         

      - name: Set up Python 
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.7
          
      - name: Install dependencies
        id: test
        run: |

             python -m pip install --urade pip  > error.log 2>&1 
            
      - name: Persist logs
        id: error
        if: ${{ failure() }}
        run: |
            echo "ERROR=$(cat error.log)" >> $GITHUB_OUTPUT
  build-f:
    runs-on: ubuntu-latest
    if: failure()
    needs: [build]
    steps:
      - name: error display
        run: |
             echo "error = ${{ needs.build.outputs.ERROR}}"
