name: unitteststg
 
on:
 push:


 

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.error.outputs.ERROR }}

    steps:
      - uses: actions/checkout@v3
      
         

      - name: Set up Python 
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.7
          
      - name: Install dependencies
        id: test
        run: |

             python3 -m pip intall  > error.log 2>&1 
            
      - name: Persist logs
        id: error
        if: ${{ failure() }}
        run: |
            #echo $(cat error.log) > logs.txt
            output="$(cat error.log)"
            output="${output//$'\n'/\\n}"
            output="${output// / }"
            #echo "ERROR<<EOF" >> $GITHUB_OUTPUT
            #echo "$output<<EOF" >> $GITHUB_OUTPUT
            #echo "EOF" >> $GITHUB_OUTPUT
            echo "ERROR=${output}" >> $GITHUB_OUTPUT
      - name: Persistd logs
        id: errors
        if: ${{ failure() }}
        run: |       
            echo "WARNING = ${{ steps.error.outputs.WARNING.replaceAll('\"', '\\\"') }}"
            
  build-f:
    runs-on: ubuntu-latest
    if: always()
    needs: [build]
    steps:
      - name: error display
        run: |
             echo  "error=${{ needs.build.outputs.output1}}"
