name: unitteststg
 
on:
 push:


 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
         

      - name: Set up Python 
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.7
          
      - name: Install dependencies
        id: test
        run: |

             python -m pip install --urade pip  > error.log 2>&1 
            
      - name: Persist logs
        id: error
        if: ${{ failure() }}
        run: |
            #echo $(cat error.log) > logs.txt
            #echo "ERROR=$(cat logs.txt)" >> $GITHUB_OUTPUT
            echo "::set-output name=error::$(cat error.log)"
  build-f:
    runs-on: ubuntu-latest
    if: failure()
    needs: [build]
    steps:
      - name: error display
        run: |
             echo "error = ${{ needs.build.outputs.error}}"
