# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
    
  push:
 
    branches: [ "main" ]
   

jobs:
  run-build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: MontyD/package-json-updated-action@1.0.1

      id: version-updated
      with:
        path: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      if: steps.version-updated.outputs.has-updated
      with:
        fetch-depth: 1
        
    - uses: actions/setup-node@v3
      if: steps.version-updated.outputs.has-updated
      with:
        node-version: '12.x'
       

    - name: Get current package version
      if: steps.version-updated.outputs.has-updated
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.2.3 
      
    - name: Update backend version
      if: steps.version-updated.outputs.has-updated
      run: echo ${{ steps.package-version.outputs.current}}
      
      
  
     
              
   
   
      
