

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: production CI
on:
  push:     
jobs:
  run-build-if-needed:
    runs-on: ubuntu-latest        
    steps:
       - uses: actions/checkout@v3
 
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
          node-version: '14'          
       - name: Install semver
         run: npm install -g semver
        
       - name: Get current package version     
         id: package-version
         uses: martinbeentjes/npm-get-version-action@v1.3.1

       - name: Increment version to release candidate
         id: increment_version
         run:  |
              echo "latest_commit=$(semver v2.3.4 -i prerelease --preid rc)" >> $GITHUB_OUTPUT
              echo $latest_commit

       - name: Output release candidate version
         run: echo "The release candidate version is ${{ steps.increment_version.outputs.latest_commit }}"  

       - name: Set Git Identity
   
         run: |         
          git config --global user.email "anuteresaj@gmail.com"
          git config --global user.name "anuteresa" 
         
       - name:  'Automated Version Bump'
         run: |  
              #npm version ${{ steps.package-version.outputs.current-version}} prerelease --preid=rc
              current_version=${{ steps.package-version.outputs.current-version}}
              rc_number=$(echo "$current_version" | grep -o 'rc[0-9]*' | grep -o '[0-9]*' | tail -1)
              if [ -z "$rc_number" ]; then
              new_rc_version="${current_version}rc1"
              else
              new_rc_number=$((rc_number + 1))
              new_rc_version=$(echo "$current_version" | sed "s/rc$rc_number/-rc$new_rc_number/")
              fi
              jq '.version = $new_version' --arg new_version "$new_rc_version" package.json > package.tmp && mv package.tmp package.json
              git commit -am "Update package.json version to $new_rc_version"
              git push
      
              

      
   #    - name: Commit changes
    #     run: |
     #      ls -la
      #     cat package.json
       #    git add package.json
        #   git status
         #  git log
          
       #- name: Push changes
        # uses: ad-m/github-push-action@master
         #with:
         # github_token: ${{ secrets.GITHUB_TOKEN }}
         
     
 


   

        

          
    

   
        
    


 
    
 
