

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: production CI

on:
  push:
   

 
        
  

jobs:
  run-build-if-needed:
    runs-on: ubuntu-latest
     
   
    steps:

       - uses: actions/checkout@v3
 
   
        
       - name: Get current package version     
         id: package-version
         uses: martinbeentjes/npm-get-version-action@v1.3.1

       - name: Increment version to release candidate
         id: increment_version
         run:  |
              echo "latest_commit=$(semver ${{ steps.version.outputs.version }} -i prerelease --preid rc)" >> $GITHUB_OUTPUT
              echo $latest_commit
         
     
 


   

        

          
    

   
        
    


 
    
 
