name: Nightly Deployment

on:
 push: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
     output1: ${{ steps.check_changes.outputs.changes_detected }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         ref: main
      - name: Set API
        run: |
              gh release view
              env:
                  GH_TOKEN: ${{ github.token }}
