name: d

on:
  push:
   tags:
    - feature*.**

jobs:
  run-build:

    runs-on: ubuntu-latest
    
               
    steps:

    - uses: actions/checkout@v3
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Current branch name
      run: |
            OLD_HEAD=$(git rev-parse HEAD)
            echo $OLD_HEAD
            git checkout {{ steps.branch-name.outputs.base_ref_branch }}
            NEW_HEAD=$(git rev-parse HEAD)
            echo $NEW_HEAD
            file=$(git diff --name-only $OLD_HEAD $NEW_HEAD | egrep 'package.json')
            if [ "$file" = "package.json" ]
            then
              echo "changed"
            else
              echo "no chnage"
            fi 
   
