name: d

on:
  push:
    
 

 
        
  

jobs:
  run-build-if-needed:
    runs-on: ubuntu-latest
     
  
               
    steps:

    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0

    - name: 'Blog Custom Github Action'
      shell: bash 
      run: |
          npm install 
          npm run build
          ls -la
          
       
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.1

      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: build
          publish_branch: 'f4'
          publish_dir: 'en'


   
