name: d

on:
  push:
    
 

 
        
  

jobs:
  run-build-if-needed:
    runs-on: ubuntu-latest
     
  
               
    steps:

    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0

    - name: 'Blog Custom Github Action'
      shell: bash 
      run: |
          npm install 
          npm run build
          ls -la
          
    - name: Push generated webpage to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.2
      env:
          API_TOKEN_GITHUB: ${{ secrets.MY_PAT }}
      with:
          source-files: 'build/'
          destination-username: 'anuteresa'
          destination-repository: 'react_ci-cd'
          destination-directory: 'ml'
   
