
name: unittestslack
 
on:
  push:


 

jobs:
  build:
    runs-on: ubuntu-22.04
   

    steps:
      
         

     
          
      - name: Install dependencies
        run: |
              echo "event name is: ${{ github.event_name }}" 
              echo "https://github.com/${{ github.repository }}"
              echo "branch name is: ${{ github.ref_name }}"
              echo "${{github.workflow}}"
              ts = Math.floor(Date.now() / 1000)
              echo "$ts"

      

             

              
             
          
               
       
             
             

