
name: unittestslack
 
on:
  push:


 

jobs:
  build:
    runs-on: ubuntu-latest
   

    steps:
      
         

     
          
      - name: Install dependencies
        run: |
              echo "event name is: ${{ github.event_name }}" 
              echo "https://github.com/${{ github.repository }}"
              echo "branch name is: ${{ github.ref_name }}"
              echo "${{GITHUB_WORKFLOW}}

      

             

              
             
          
               
       
             
             

