
name: unittest
 
on:
  push:
    #tags:
     # - v*.**

 

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: m

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: create .env
        run: |
             touch .env
             ls -la

             
          
      
      - name: Get specific changed files
        run: |

             sudo chmod +x setup.sh
             OLD_HEAD=$(git rev-parse HEAD)
             ./setup.sh
             NEW_HEAD=$(git rev-parse HEAD)
             

              
             
          
               
       
             
             

