
name: unittest
 
on:
  push:


 

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: m
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: m

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
         

      - name: Set up Python 
        uses: actions/setup-python@4.3.0
        with:
          python-version: 3.
          
      - name: Install dependencies
        run: |
         sudo apt-get update && sudo apt install libcairo2
         python -m pip install --upgrade pip
         

      

             

              
             
          
               
       
             
             

