
name: unittest
 
on:
  push:
    tags:
      - v*.**

 

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: m
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: m

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
         

      - name: Set up Python 
        uses: actions/setup-python@4.3.0
        with:
          python-version: 3.
          
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         
      - name: Copy a .env file from s3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
         command: cp
         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws_region: eu-central-1
         source: 's3://'
         dest: './'
         
      - name: Rename the file to .env
        run: |
             mv be .env     

      - name: Test with Unittest
        env:
         POSTGRES_HOST: localhost
         POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
         python manage.py test      
          
      

             

              
             
          
               
       
             
             

