
name: unittest
 
on:
  push:
    tags:
      - v*.**

 

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: m

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Copy a file from s3
        uses: prewk/s3-cp-action@v2
        with:
         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         source: 's3://some-bucket/something-remote'
         dest: './'

      - name: Set up Python 
        uses: actions/setup-python@4.3.0
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip

      - name: Test with Unittest
        run: |
         python manage.py test      
          
      
      - name: Get specific changed files
        run: |

             sudo chmod +x setup.sh
             OLD_HEAD=$(git rev-parse HEAD)
             ./setup.sh
             NEW_HEAD=$(git rev-parse HEAD)
             

              
             
          
               
       
             
             

