on:
  push:
    tags:
      - "v*"
    branch:
      - main
  

jobs:
  version-check:
    runs-on: ubuntu-latest
   # outputs:
      #output1: ${{ steps.get_version.outputs.VERSION }}
    
    steps: 
   
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false           
  version:
     if: success()
     needs: [version-check]
     runs-on: ubuntu-latest
   # outputs:
      #output1: ${{ steps.get_version.outputs.VERSION }}
    
     steps: 
   
       
      - uses: actions/checkout@v3
      - name: Get current package version
        
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1 
      - name: vvversion 
        run: 
          echo "version =${{ steps.package-version.outputs.current-version}}" 
     
