on:
  push:
   tags:
      - 'v*' 
  

jobs:
  version-check:
    runs-on: ubuntu-latest
   # outputs:
      #output1: ${{ steps.get_version.outputs.VERSION }}
    
    steps: 
   
       
      - uses: actions/checkout@v3
        with:
          ref: main
          
          

      - name: Get current package version
        
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1  
      - name: vvversion 
        run: 
          echo "version =${{ steps.package-version.outputs.current-version}}" 
      - name: Create Release
        id: create_release   
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: production${{ steps.package-version.outputs.current-version}}
          draft: false
          prerelease: false

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false  
          title: production${{ steps.package-version.outputs.current-version}}
  version:
     if: success()
     needs: [version-check]
     runs-on: ubuntu-latest
   # outputs:
      #output1: ${{ steps.get_version.outputs.VERSION }}
    
     steps: 
   
       
      - uses: actions/checkout@v3
      - name: Get current package version
        
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1 
      - name: vvversion 
        run: 
          echo "version =${{ steps.package-version.outputs.current-version}}" 
     